services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    volumes:
      - prometheus-storage:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart:
      unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin #Change this to a strong password
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=example@gmail.com # Add a Gmail email (Change in contact-points.yaml too)
      - GF_SMTP_PASSWORD=aaaa aaaa aaaa aaaa # Use App Password if 2FA is enabled
      - GF_SMTP_SKIP_VERIFY=false
      - GF_SMTP_FROM_ADDRESS=example@gmail.com
      - GF_SMTP_FROM_NAME=Dev Grafana Alerts
    volumes:
        - grafana-storage:/var/lib/grafana
        - ./grafana/provisioning:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    networks:
      - monitoring-network
    depends_on:
      - prometheus

volumes:
    grafana-storage:
    prometheus-storage:

networks:
  monitoring-network:
    driver: bridge