apiVersion: 1
groups:
  - orgId: 1
    name: user-service
    folder: User Service Alerts
    interval: 10s
    rules:
      - uid: getallusers-slow
        title: getAllUsers avg > 500 ms (1m)
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus-datasource
            model:
              datasource:
                type: prometheus
                uid: prometheus-datasource
              expr: |
                ( rate(user_service_method_time_seconds_sum{method="getAllUsers"}[1m])
                / rate(user_service_method_time_seconds_count{method="getAllUsers"}[1m]) ) * 1000
              interval: ""
              intervalMs: 1000
              legendFormat: ""
              maxDataPoints: 43200
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: last
              refId: B
              type: reduce
          - refId: C
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 500
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - B
                  reducer:
                    type: last
              expression: B
              intervalMs: 1000
              maxDataPoints: 43200
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 10s
        annotations:
          description: 1m moving average > 500 ms. Value={{ $values.B.Value }} ms
          summary: getAllUsers() is slow
        labels:
          method: getAllUsers
          service: user
          severity: warning
        isPaused: false
